In [511]:
'''
CISC 452 Perceptron
Harry Kim 
20047381
same code as multiclass_perceptron but using the pocket algorithim
'''


&#39;\nTHIS IS A WORKING PERCEPTRON OF A BINARY CLASSIFICIATION\n&#39;

In [512]:
#libararies that allow easier handling of the data and visualization. Not importing anything for the model itself. 

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder 
import random as random 

#data preprocessing
train_set = open("iris_train.txt","r")
test_set = open('iris_test.txt','r')

def preprocess(data):
    df = pd.DataFrame(columns=['sepal_length','sepal_width','petal_lenght','petal_width','iris_type'])

    #cleaning up data and putting it in df
    for i in data:
        i = i.strip()   #get rid of \n 
        lst= i.split(",") #split the string into list
        df = df.append({'sepal_length':float(lst[0]), 'sepal_width':float(lst[1]),'petal_lenght':float(lst[2]),'petal_width':float(lst[3]),'iris_type':lst[4]},ignore_index=True)

    #since the target label has three string type categorical data, we will turn it into numerical using label encoder
    df['iris_type']= LabelEncoder().fit_transform(df['iris_type']) #need to turn it into label encoder to turn it into one hot
    df =pd.get_dummies(df, columns = ['iris_type']) #one hot encoding
    return df 

df_train = preprocess(train_set)
df_test = preprocess(test_set)


In [ ]:
#visualization DONT RUN FOR MARKING, EXPENSIVE TO RUN
# iris = df.copy()
# import matplotlib.pyplot as plt

# attributes = ['sepal_length','sepal_width','petal_lenght','petal_width'] 
# iris = iris[attributes].astype(np.float)

# # iris.hist(bins=50, figsize=(20,15)) 
# # plt.show()

In [513]:
#preprocessing
from sklearn import preprocessing

def min_max(df):
    y = df.iloc[:,4:]
    x = df.iloc[:,0:4].values #returns a numpy array
    min_max_scaler = preprocessing.MinMaxScaler(feature_range=(-1, 1))
    x_scaled = min_max_scaler.fit_transform(x)
    df_ = pd.DataFrame(x_scaled)
    df_ = df_.join(y)
    return df_

# df_train = min_max(df_train)
# df_test = min_max(df_test)

# print(df_train)

In [514]:
class Perceptron:

    def __init__(self, epoch=100, c=0.1):
        self.epoch = epoch
        self.c = c  #learning rate
        self.weights = self.random_weights() #creates an np array of zeros, +1 is from the x0=1 bias vector ###make this random instead
    
    def random_weights(self):
        #creates random weights
        rand_array = [0] #first weight of 0 that is from the bias
        #Four input nodes, four weights
        for i in range(4):
            rand_array.append(random.uniform(-1, 1))
        return np.asarray(rand_array)


    def activation(self, x):
        #the weights[0] is the bias . The dot product finds the net input (sigma wx) 
        return np.dot(x, self.weights[1:]) + self.weights[0]

    def predict(self, x):
        #predict y - f(sigma(xw))
        return np.where(self.activation(x) >= 0.0, 1, 0)

    def learning(self, d, y, x):
        #feeback learning 
        if y > d: #y =1 d = 0 
            self.weights[1:] = self.weights[1:] - self.c * x #adjusting the weights
            self.weights[0] = self.weights[0] - self.c #adjust the bias, x is 1 no need to put it in

        elif y < d: #y= 0 d = 1
            self.weights[1:] = self.weights[1:] + self.c * x
            self.weights [0] = self.weights[0] + self.c 


    def fit(self, total_x, total_d): 
        turn = int(self.epoch) 
        for _ in range(turn):
            for x, d in zip(total_x, total_d): #zip creates list at (x[n],y[n]) for all values in x and y, iterable
                y = self.predict(x)
                self.learning(int(d),int(y),x)
                

In [515]:
class Multiclass_Perceptron:
    def __init__(self, epoch = 100, c= 0.1):
        #each perceptron does binary classification for their corresponding flowers
        self.output1 = Perceptron(epoch,c) 
        self.output2 = Perceptron(epoch,c) 
        self.output3 = Perceptron(epoch,c) 

    def predict(self, x):
        output1_pred = self.output1.predict(x.values) #this will be a list of all prediction just for the one corresponding column 
        output2_pred = self.output2.predict(x.values)
        output3_pred = self.output3.predict(x.values)

        #format it as a list of list 
        aList = []
        for i in range(len(x)):
            bList= [output1_pred[i],output2_pred[i],output3_pred[i]]
            aList.append(bList)
        return np.array(aList)

    def fit(self, total_x, total_d): 
        #.values converts the pandas column into numpyarray 
        #.iloc grabs the corresponding binary class column for each 
        self.output1.fit(total_x.values, total_d.iloc[ : ,0].values) #train binary classification for flower 1
        self.output2.fit(total_x.values, total_d.iloc[ : ,1].values) #train binary classification for flower 2
        self.output3.fit(total_x.values, total_d.iloc[ : ,2].values) #train binary classification for flower 3

In [516]:
#partitioning data into target and predictors for training 

df_train = df_train.sample(frac=1) #randomize the rows for training 
y_train = df_train.iloc[:, 4:7] #grab the class label 
x_train = df_train.iloc[:, 0:4] #grab the predictors

y_test = df_test.iloc[:, 4:7].values #grab the class label 
x_test = df_test.iloc[:, 0:4] #grab the predictors

[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 1 0]
[1 1 0]
[0 1 0]
[0 0 0]
[0 1 0]
[0 1 0]
[0 0 0]
[0 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 0]
[0 1 1]
[0 1 0]
[0 1 1]
[0 0 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
Data: sepal_length    4.4
sepal_width     2.9
petal_lenght    1.4
petal_width     0.2
Name: 8, dtype: float64
Actual: [1 0 0] predicted: [1 1 0]
Data: sepal_length    4.9
sepal_width     3.1
petal_lenght    1.5
petal_width     0.1
Name: 9, dtype: float64
Actual: [1 0 0] predicted: [1 1 0]
Data: sepal_length    6.4
sepal_width     2.8
petal_lenght    5.6
petal_width     2.1
Name: 21, dtype: float64
Actual: [0 0 1] predicted: [0 1 1]
Data: sepal_length    7.4
sepal_width     2.8
petal_lenght    6.1
petal_width     1.9
Name: 23, dtype: float64
Actual: [0 0 1] predicted: [0 1 1]


In [ ]:
#Testing the model
classifier = Multiclass_Perceptron(epoch = 1000, c= 0.5)
classifier.fit(x_train,y_train) 

#predict
y_pred = classifier.predict(x_test)

#find data points that are classified into multiple classes
multiple_pred_index = [] 
for i in range(len(y_pred)):
    output = y_pred[i]
    print(output)
    x = output[0] + output[1] + output[2]
    if x > 1:
        multiple_pred_index.append(i)

#Grab the corresponding data from test set
for i in multiple_pred_index:
    print("Data:",x_test.iloc[i])
    print('Actual:', y_test[i], "predicted:",y_pred[i])

In [517]:
#Getting Accuracy and Confusion Matrix
from sklearn.metrics import accuracy_score, multilabel_confusion_matrix, precision_score, recall_score, confusion_matrix

print("accuracy", accuracy_score(y_test,y_pred))
print('confusion matrix', multilabel_confusion_matrix(y_test,y_pred))



accuracy 0.6
confusion matrix [[[20  0]
  [ 0 10]]

 [[13  7]
  [ 3  7]]

 [[20  0]
  [ 5  5]]]


ValueError: multilabel-indicator is not supported

[[0, 3], [1, 4], [2, 5]]
